# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'say_goodbye']

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello, {to}!'

def say_goodbye(to):
    "Say goodbye to somebody"
    return f'See ya, {to}!'